# Site
name: INUCEM
description: Incheon National University Construction Engineering & Management Laboratory
meta_description: "Incheon National University CEMLAB."
logo: 'assets/images/logo_2.png'{: width="238" height="30"} # 화면 왼쪽 상단 연구실 아이콘 모양 238*30
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: 
email: 'mkim105@hawk.iit.edu'
google_analytics: 'UA-115605548-1'
disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  INUCEM:
    name: INUCEM
    display_name: INUCEM
    gravatar: 
    email:
    web: 
    twitter: 
    description: 
  Minguk:
    name: Minguk Kim
    display_name: Minguk
    gravatar: 
    email:
    web: 
    twitter: 
    description: 

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
